name: Build
on:
    push:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-on-alpine:
        name: alpine_x86_64
        runs-on: ubuntu-latest
        container:
            image: nicolassqreen/azure-pipelines-container-alpine-python:3.12
        timeout-minutes: 180
        steps:
            - name: Clone repository
              uses: actions/checkout@v1

            - name: Download V8 sources
              uses: docker://python:2
              with:
                  args: python helpers/v8_build.py --no-build --no-sysroot

            - name: Prepare Aline Linux build environment
              run: |
                  sudo apk -U add samurai llvm lld linux-headers binutils-gold
                  cp -f /usr/local/bin/gn py_mini_racer/extension/v8/buildtools/linux64/gn
                  rm -f py_mini_racer/extension/depot_tools/ninja

            - name: Build the extension
              run: |
                  python helpers/v8_build.py --no-update --no-sysroot --target py_mini_racer_shared_lib
                  cp py_mini_racer/extension/out/libmini_racer.so py_mini_racer/libmini_racer.muslc.so

            - name: Build the wheelhouse
              run: |
                  sudo apk add py3-pip py3-wheel
                  mkdir wheelhouse
                  python3 setup.py sdist --dist-dir wheelhouse

            - name: Archive wheelhouse
              uses: actions/upload-artifact@v2
              with:
                  name: package-alpine_x86_64
                  path: wheelhouse

            - name: Test
              run: |
                  python3 -m pip install pytest wheelhouse/*.tar.gz
                  pytest tests

    # release:
    #     if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    #     runs-on: ubuntu-latest
    #     needs: [build-on-alpine, build]
    #     steps:
    #      - name: Download packages
    #        uses: actions/download-artifact@v2
    #        with:
    #            path: tmp

    #      - name: Move packages to the wheelhouse
    #        run: |
    #          mkdir wheelhouse
    #          find tmp -name '*.whl' -exec mv {} wheelhouse \;
    #          find tmp -name '*.tar.gz' -exec mv {} wheelhouse \;
    #        shell: bash

    #      - name: Publish 📦 to PyPI
    #        uses: pypa/gh-action-pypi-publish@v1.4.2
    #        with:
    #          user: __token__
    #          password: ${{ secrets.PYPI_TOKEN }}
    #          packages_dir: wheelhouse/
